// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,if:64, let:66, "let*":68, lambda:70, cond:72, use:74, namespace:76, implements:78, bless:80, "with-read":82, "with-default-read":84, "with-capability":86, bind:88, step:90, "step-with-rollback":92, resume:94, yield:96, enforce:98, "enforce-one":100, "enforce-keyset":102, "enforce-guard":104, "require-capability":106, "compose-capability":108, read:110, write:112, update:114, select:116, where:118, and:120, or:122, not:124, try:126, format:128, map:130, fold:132, filter:134, "define-keyset":136, "define-namespace":138, defun:140, defcap:142, defconst:144, defpact:146, defschema:148, deftable:150, module:152, interface:154, defproperty:156, integer:158, decimal:160, time:162, bool:164, string:166, list:168, value:170, keyset:172, guard:174, object:176, table:178, true:180, false:182}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bQYQPOOO%vQPO'#ClO%}QPO'#CoO&UQQO'#CrOOQO'#C{'#C{OOQO'#Cv'#CvQYQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Cb'#CbOOQO'#Cc'#CcOOQO,59W,59WO&^QPO,59WOOQO,59Z,59ZO&eQPO,59ZO&lQQO'#CwO&qQQO,59^OOQO,59^,59^OOQO-E6t-E6tOOQO1G.r1G.rOOQO1G.u1G.uOYQPO,59cOOQO-E6u-E6uOOQO1G.x1G.xO&yQQO1G.}OOQO7+$i7+$i",
  stateData: "'Z~OnOSPOS~OSSOWSOXSOYSOZSO[SO]SO_PObQOeROpVOqVOrVOsVOtVOuVOvVOwVOxVOyVOzVO{VO|VO}VO!OVO!PVO!QVO!RVO!SVO!TVO!UVO!VVO!WVO!XVO!YVO!ZVO![VO!]VO!^VO!_VO!`VO!aVO!bVO!cVO!dVO!eVO!fVO!gVO!hWO!iWO!jWO!kWO!lWO!mWO!nWO!oWO!pWO!qXO!rXO!sXO!tXO!uXO!vXO!wXO!xXO!yXO!zXO!{XO!|YO!}YO~O^ZO~PYOa]O~PYOdaOg_O~O^cO~PYOadO~PYOheO~OdgOg_O~OiiOdkigki~OXW]W~",
  goto: "!kpPPPqPqqqPPPPPPPPqPPqPPqPPPz!YPPP!`_SOPQU[^eQUOQ[PQ^QVbU[^Q`RRf`[TOPQU[^Rhe",
  nodeNames: "⚠ LineComment Program Keyword Identifier DefKeyword TypeKeyword Boolean Number Decimal String Symbol MetaTag Operator ) ( Application ] [ List } { Object PropertyName : ,",
  maxTerm: 91,
  nodeProps: [
    ["openedBy", 14,"(",17,"[",20,"{"],
    ["closedBy", 15,")",18,"]",21,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: ".k~RlXY!yYZ!y]^!ypq!yqr#[rs#iwx'cxy(Wyz(]z{#[{|#[|}(b}!O(g!P!Q#[!Q![)T![!])n!]!^)y!^!_#[!_!`#[!`!a#[!b!c*h!c!}+Y!}#O.V#P#Q.[#R#S+Y#T#o+Y#o#p.a#q#r.f~#OSn~XY!yYZ!y]^!ypq!yP#aP]P!_!`#dP#iO]PR#nagQOr$srs&as}$s}!O#i!O!Q$s!Q![#i![!c$s!c!}#i!}#O$s#O#P%b#P#R$s#R#S#i#S#T$s#T#o#i#o;'S$s;'S;=`&Z<%lO$sP$vVOr$srs%]s#O$s#O#P%b#P;'S$s;'S;=`&Z<%lO$sP%bOYPP%eRO;'S$s;'S;=`%n;=`O$sP%qWOr$srs%]s#O$s#O#P%b#P;'S$s;'S;=`&Z;=`<%l$s<%lO$sP&^P;=`<%l$sR&hUgQYPrs&z}!O&z!Q![&z!c!}&z#R#S&z#T#o&zQ'PUgQrs&z}!O&z!Q![&z!c!}&z#R#S&z#T#o&z~'fS}!O'r!c!}'r#R#S'r#T#o'r~'wTZ~}!O'r!Q!['r!c!}'r#R#S'r#T#o'r~(]O_~~(bO^~~(gOi~R(nVgQ]Prs&z}!O&z!Q![&z!_!`#d!c!}&z#R#S&z#T#o&z~)YQW~!O!P)`!Q![)T~)cP!Q![)f~)kPX~!Q![)fR)sQhQ![!]#d!_!`#d~)|P!]!^*P~*USP~OY*PZ;'S*P;'S;=`*b<%lO*P~*eP;=`<%l*P~*kR!c!}*t#R#S*t#T#o*t~*yT[~}!O*t!Q![*t!c!}*t#R#S*t#T#o*tR+aeSPgQqr,rrs&zst,rtu,ruv,rvw,rz{,r{|,r}!O+Y!O!P,r!P!Q,r!Q![+Y!^!_,r!_!`,r!`!a,r!a!b,r!b!c,r!c!}+Y#R#S+Y#T#o+Y#p#q,rP,wdSPqr,rst,rtu,ruv,rvw,rz{,r{|,r}!O,r!O!P,r!P!Q,r!Q![,r!^!_,r!_!`,r!`!a,r!a!b,r!b!c,r!c!},r#R#S,r#T#o,r#p#q,r~.[Ob~~.aOa~~.fOe~~.kOd~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 282
})
